---
sudo: required
language: python
python:
    - "2.7"

services:
  - docker

env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING="False"

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible docker-py
  - ansible --version
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles/


script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --skip-tags=rpi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/