---
- name: Create database
  become: true
  file:
    name: "{{ mage_zabbix_db_folder }}/{{ mage_zabbix_db_file_name }}"
    owner: zabbix
    group: zabbix
    state: touch

- name: Check if DB already exists
  become: true
  stat:
    path: "{{ mage_zabbix_db_folder }}/{{ mage_zabbix_db_file_name }}"
  register: zabbix_db_exists
  tags: ['db_deploy']

- name: Unpack DB schema
  become: true
  shell: zcat /usr/share/doc/zabbix-proxy-sqlite3/schema.sql.gz > /tmp/zabbixschema.sql
  when: mage_zabbix_db_overwrite or zabbix_db_exists.stat.exists == False or zabbix_db_exists.stat.size == 0
  tags: ['db_deploy']
  
- name: Import schema
  become: true
  shell: "sqlite3 {{ mage_zabbix_db_folder }}/{{ mage_zabbix_db_file_name }} < /tmp/zabbixschema.sql"
  when: mage_zabbix_db_overwrite or zabbix_db_exists.stat.exists == False or zabbix_db_exists.stat.size == 0
  tags: ['db_deploy']
  
- name: Change ownership of the db to zabbix user
  become: true
  file:
    path: "{{ mage_zabbix_db_folder }}/{{ mage_zabbix_db_file_name }}"
    owner: zabbix
    group: zabbix